# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 200
paginate_path: "/page:num/" # jekyll-paginate > blog page
gems:
  - jekyll-paginate
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: ailswan # jekyll-seo-tag > Owners twitter username
author: ailswan # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: ailswan # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/ailswan
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike
highlighter: rouge


# 5. Collections
collections:
  posts:
    title: List of all posts # Needed for Siteleaf
    output: true
    description: "List according dates" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
  poststwo:
    title: List of all postsTwo
    output: true
    description: "List according dates"
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=865"
  essays:
    title: List of all essays  
    output: true
    description: "List according dates"  
    feature_text: |
      Welcome to the essays & notes
    feature_image: "https://picsum.photos/2560/600?image=872"
  topics:
    title: List of all tech topics
    output: true
    description: "List according tech topics"
    feature_text: |
      Welcome to the sd tech topics & notes
    feature_image: "https://picsum.photos/2560/600?image=872" 
  tradeoff:
    title: List of all tradeoff  
    output: true
    description: "List according tradeoff"
    feature_text: |
      Welcome to the sd tradeoff & notes
    feature_image: "https://picsum.photos/2560/600?image=872" 
  technology:
    title: List of all techonology  
    output: true
    description: "List according techonology"
    feature_text: |
      Welcome to the sd techonology 
    feature_image: "https://picsum.photos/2560/600?image=872" 
  strategy:
    title: List of all strategies  
    output: true
    description: "List according strategies"
    feature_text: |
      Welcome to the sd strategies 
    feature_image: "https://picsum.photos/2560/600?image=872" 
  tool:
    title: List of all tools  
    output: true
    description: "List according tools"
    feature_text: |
      Welcome to the sd tools 
    feature_image: "https://picsum.photos/2560/600?image=872" 

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page  
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: topic
  -
    scope:
      path: ""
      type: "tradeoff"
    values:
      layout: tradeoff
  -
    scope:
      path: ""
      type: "technology"
    values:
      layout: technology
  -
    scope:
      path: ""
      type: "strategy"
    values:
      layout: strategy
  -
    scope:
      path: ""
      type: "tool"
    values:
      layout: strategy

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "AilswanCoding" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: " " # Site description and default description, also used in jekyll-seo-tag
url: "https://ailswan.coding" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/ailswan"
email: "ailswanster@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Java
  url: /Java/
- title: KnowledgeMap
  url: /knowledgemap/
- title: Essayslist
  url: /essayslist/
- title: Categories
  url: /categories/
- title: Search
  url: /search/
- title: Fork ailswan
  url: https://github.com/ailswan/ailswan.github.io

navigation_footer:
- title: Created by ailswan
  url: https://github.com/ailswan

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com 
  LinkedIn: https://www.linkedin.com
  GitHub: https://github.com/ailswan
  link: https://github.com/ailswan
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "0"
  facebook: "0"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
liquid:
  loops:
    max: 200